version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "\u001bpi]"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o6brgnq2hbec"
s3_prefix = "\u001bpi]"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

